### ISSUE TITLE
Lỗi: Không tìm thấy $array_config['maxfilesize'] khi thêm dự án có đính kèm file module project.

### ISSUE THREAD

**Issue by huuthoqt1994** [mynukeviet/lynx#103]
![image](https://user-images.githubusercontent.com/14935240/56267543-4e76dc80-6119-11e9-8f87-ab9c02cbd19b.png)

**Comment by huuthoqt1994** [comment]
ở file content của dự án project.

**Comment by mynukeviet** [comment]
Đã sửa https://github.com/mynukeviet/lynx/commit/d9230bd871d1aa2dc46be3b8806fa76152e0f090
