### ISSUE TITLE
customer-detail: khi click vào tab chức năng giao diện bị đẩy xuống

### ISSUE THREAD

**Issue by huuthoqt1994** [mynukeviet/lynx#110]
![image](https://user-images.githubusercontent.com/14935240/56663325-03883680-66d0-11e9-9883-aaac5d2c71a0.png)

**Comment by hy3n0945972902v** [comment]
http://code.mynukeviet.net/themes/dashboard/commit/16b49a9ffa6b95bed8299ff257440a05dfd3c8e5

**Comment by huuthoqt1994** [comment]
Kiểm tra lại vẫn bị
