### ISSUE TITLE
Thừa trường dữ liệu

### ISSUE THREAD

**Issue by motcaiten** [mynukeviet/lynx#115]
Trong gói dữ liệu mẫu có trường trading_person,unit_name, tax_code, address_invoice của module customer nhưng ở trong module loại bỏ trường này hoặc chưa thêm nên khi add customer bị lỗi.

**Comment by mynukeviet** [comment]
Cảm ơn bạn, đã sửa https://github.com/mynukeviet/lynx/commit/71041e17d2d0155216852c53b5b765aae68c74f5
