### ISSUE TITLE
services: trường ghi chú thêm editor

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#117]

**Comment by huuthoqt1994** [comment]
sản phẩm cũng có làm theo không anh ?

**Comment by mynukeviet** [comment]
ok làm luôn cho sản phẩm

**Comment by mynukeviet** [comment]
https://github.com/mynukeviet/lynx/commit/a1a271a8e9fd3d3986b21d7ba0311f2ac84204a4
