### ISSUE TITLE
workforce : Thiếu table 

### ISSUE THREAD

**Issue by motcaiten** [mynukeviet/lynx#131]
Thiếu table nv4_vi_workforce_field

**Comment by huuthoqt1994** [comment]
Em có test lại thấy chạy file workforce vẫn tạo được 2 bảng field và info bình thường anh nha.

**Comment by mynukeviet** [comment]
Chào bạn, lỗi này do hôm qua mình chưa kịp cập nhật lại CSDL mẫu.

Có 2 phương án thế này nhé:

Phương án 1: Bạn thực thi 2 URL này để nâng cấp CSDL hiện có 
domain/crm.update.php
domain/workforce.update.php
(Hiển thị OK là được)

Phương án 2: Cập nhật lại code mới nhất, sau đó cài lại websitte

Hướng dẫn trên cũng sẽ xử lý cho issue https://github.com/tdfoss/lynx/issues/129
