### ISSUE TITLE
Customer: Lỗi khi để trông dữ liệu tài khoản

### ISSUE THREAD

**Issue by HQuang** [mynukeviet/lynx#147]
![image](https://user-images.githubusercontent.com/17137922/59499858-7937a400-8ec2-11e9-9d40-3869404f546f.png)

> Có thể để trống tên truy cập và mật khẩu nếu muốn tạo ngẫu nhiên

Ghi chú là để trống mà trong code lại bắt lỗi ngay khi lấy dữ liệu thì tự tạo như thế nào hè ?

https://github.com/tdfoss/lynx/blob/develop/modules/customer/funcs/content.php#L246-L257

**Comment by HQuang** [comment]
https://github.com/tdfoss/lynx/blob/develop/modules/customer/funcs/content.php#L421

require_once module email, ko có module email >> gây lỗi 

Thêm kiểm tra module email trước require_once

**Comment by mynukeviet** [comment]
> Ghi chú là để trống mà trong code lại bắt lỗi ngay khi lấy dữ liệu thì tự tạo như thế nào hè ?

à đúng chổ ni là có thể để trống mật khẩu thôi, đã sửa lang https://github.com/tdfoss/lynx/commit/e6148435eef694586da934e440f912eaa37d0eb3

**Comment by mynukeviet** [comment]
> https://github.com/tdfoss/lynx/blob/develop/modules/customer/funcs/content.php#L421
> 
> require_once module email, ko có module email >> gây lỗi
> 
> Thêm kiểm tra module email trước require_once

Trong lynx luôn có module email, em đang test ở hệ thống mô đó?

**Comment by HQuang** [comment]
Bữa em test cái customer lấy cái thêm tài khoản qua thiết bị trường học thì thấy lỗi

**Comment by mynukeviet** [comment]
Thiết bị ko có module email, lỗi đúng rồi
