### ISSUE TITLE
invoice: khi chọn các dịch vụ, sản phẩm thông tin tổng tiền không hiển thị

### ISSUE THREAD

**Issue by huuthoqt1994** [mynukeviet/lynx#153]
![image](https://user-images.githubusercontent.com/14935240/60065506-4301ec00-972e-11e9-9a42-e64a6b071b2d.png)

**Comment by mynukeviet** [comment]
Kéo bản mới nhất, Ctrl + F5 coi thử nghe. Chổ ni anh có sửa cái định dạng giá tiền hôm trước, đang thấy ổn.

**Comment by huuthoqt1994** [comment]
em đã check lại hoạt động ổn.
