### ISSUE TITLE
Thêm nhân sự: thêm tùy chọn tạo tài khoản khi thêm nhân sự

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#17]

**Comment by huuthoqt1994** [comment]
Đã xong https://github.com/huuthoqt1994/lynx/commit/a90972091c0a84f7747b58a1f39f5a1d54ae67d3
và đã update lại kho code nhân sự.

**Comment by mynukeviet** [comment]
Răng a thấy vẫn đang là lynx

**Comment by huuthoqt1994** [comment]
đã chuyển vào module workforce và fix lỗi. https://github.com/huuthoqt1994/module-workforce/commit/ed60849ff1138f54492128ba0c9023fab0915f05
