### ISSUE TITLE
Lỗi cài đặt

### ISSUE THREAD

**Issue by motcaiten** [mynukeviet/lynx#177]
Lỗi cài đặt tại step 6 

SQLSTATE[HY000]: General error: 1364 Field 'address' doesn't have a default value

**Comment by mynukeviet** [comment]
Đã sửa https://github.com/tdfoss/lynx/commit/40b42b9b8b1f9cbbb37d163d9f878e83500f731e

Nhờ bạn download lại thử lại giúp mình với nhé

**Comment by motcaiten** [comment]
> Đã sửa [40b42b9](https://github.com/tdfoss/lynx/commit/40b42b9b8b1f9cbbb37d163d9f878e83500f731e)
> 
> Nhờ bạn download lại thử lại giúp mình với nhé

Đã ok. 

Trong phần customer . Khi xem chi tiết khách hàng và tạo sự kiện bị lỗi. Nó load ra trang chủ.

**Comment by mynukeviet** [comment]
Ô xin lỗi bạn, có thiếu sót. Bạn kéo về cài lại giúp mình nhé.

**Comment by motcaiten** [comment]
Đã ok.
