### ISSUE TITLE
invoice: mô tả nhập enter nhưng khi hiển thị chi tiết bị dồn hàng

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#23]
![screenshot from 2018-08-02 15-45-23](https://user-images.githubusercontent.com/6407361/43573061-195ad0de-966b-11e8-9075-ba8164aebc0e.png)

**Comment by huuthoqt1994** [comment]
cái điểu khoản sử dụng cũng bị vậy có thay đổi không anh ?
