### ISSUE TITLE
workreport: thêm cột tổng giờ làm ra danh sách, tổng giờ làm ở cuối trang

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#25]

**Comment by huuthoqt1994** [comment]
tồng giờ làm như thế này hả anh ?
![image](https://user-images.githubusercontent.com/14935240/43764351-6f4c2aca-9a57-11e8-877a-f84db0f855d1.png)

**Comment by mynukeviet** [comment]
Um, đúng rồi em
