### ISSUE TITLE
products: sai thông tin logs

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#43]
1. "He thong" có vẻ đang viết trong code
2. Người thực hiện là Hồ Ngọc Triển mới đúng

![screenshot from 2018-08-16 09-05-15](https://user-images.githubusercontent.com/6407361/44183012-8c0f0a00-a133-11e8-9e3d-e627d174bc2e.png)

**Comment by huuthoqt1994** [comment]
Em thấy ghi đúng rồi mà, cái log anh xem nằm ở đâu vậy anh .
![image](https://user-images.githubusercontent.com/14935240/44613459-e009a500-a83d-11e8-91f0-47d654e451f4.png)

**Comment by mynukeviet** [comment]
Cái chữ "He thong" thì anh sửa rồi, còn cái ý thứ 2 giờ hắn mất rồi nên anh ko test lại đc, em coi thử
