### ISSUE TITLE
Góp ý

### ISSUE THREAD

**Issue by motcaiten** [mynukeviet/lynx#48]
Trong phần khách hàng nên để chỗ khách hàng nên liên kết với tài khoản thành viên như nhân sự. Và chỗ dự án thì sẽ phần quyền cho khách hàng được comment trong dự án được phân quyền

**Comment by mynukeviet** [comment]
> Trong phần khách hàng nên để chỗ khách hàng nên liên kết với tài khoản thành viên như nhân sự

Cái này mình có tính đến, nhưng hiện tại lynx chưa lập trình khu vực cho khách hàng truy cập nên mình chưa đụng tới cái này. Chừng nào phát triển xong phần để khách hàng truy cập thì sẽ có liên kết tài khoản để họ đăng nhập bạn nhé

> Và chỗ dự án thì sẽ phần quyền cho khách hàng được comment trong dự án được phân quyền

Sẽ phát triển

**Comment by mynukeviet** [comment]
Đã thêm cho lynx-pro
