### ISSUE TITLE
projects: Lỗi không thêm dự án mới

### ISSUE THREAD

**Issue by hy3n0945972902v** [mynukeviet/lynx#51]

**Comment by huuthoqt1994** [comment]
Là răng Hiền mô tả ra em.

**Comment by mynukeviet** [comment]
Sau khi thêm thì hắn có hiện tượng ra răng mô tả để  dễ test hơn luôn @hy3n0945972902v

**Comment by mynukeviet** [comment]
Do chưa chạy update đúng ko @hy3n0945972902v ?
