### ISSUE TITLE
Không gửi được email cho khách hàng

### ISSUE THREAD

**Issue by thanhchunghti** [mynukeviet/lynx#56]
Trong phần cấu hình em đã cấu hình đúng như web khác đang làm nhưng không gửi được.
smtp.yandex.com
Cổng 587
Tên tài khoản
mật khẩu
 Như web kia, trong phần Liên hệ/Gửi phản hồi. Em cấu hình như vậy thì có thể gửi đi bình thường. Nhờ anh xem giúp.

**Comment by thanhchunghti** [comment]
Anh có thể nói qua cách logs được ko ạ :3 
Em gà mờ quá nên ko rõ mấy cái này

**Comment by mynukeviet** [comment]
Bạn gửi file **data/logs/error_logs/xxx.logs** với xxx là ngày bị lỗi

**Comment by thanhchunghti** [comment]
Đây anh ơi

> [Mon, 27 Aug 2018 08:46:26 +0700] [nguoidanang.vn] [27.66.86.166] [Notice(8): Undefined index: userid] [FILE: /modules/email/functions.php] [LINE: 16]
[Mon, 27 Aug 2018 08:46:26 +0700] [nguoidanang.vn] [27.66.86.166] [Notice(8): Undefined offset: 0] [FILE: /themes/simple/blocks/global.bootstrap.php] [LINE: 116]
[Mon, 27 Aug 2018 08:46:26 +0700] [nguoidanang.vn] [27.66.86.166] [Warning(2): Invalid argument supplied for foreach()] [FILE: /themes/simple/blocks/global.bootstrap.php] [LINE: 116]

**Comment by mynukeviet** [comment]
Cái này bạn xem lại cấu hình mail nhé, chú hệ thống không có lỗi gì đâu ạ

**Comment by mynukeviet** [comment]
Xác định chổ này chỉ do cấu hình email nên mình sẽ đóng issue nhé
