### ISSUE TITLE
Góp ý chút. 

### ISSUE THREAD

**Issue by motcaiten** [mynukeviet/lynx#57]
Sau mấy ngày xài CRM bên BĐS mình thấy chỗ này quan trọng với 1 CRM nếu nhiều nhân viên Sale. Đó là vấn đề phân quyền để nhân viên đó chỉ thấy thông tin của khách hàng họ add và chỉ có quản lí mới thấy được toàn bộ khách hàng của các nhân viên.

Thứ 2 là nếu admin thêm khách thì sẽ phân bố khách đó cho 1 nhân viên cụ thể nào đó chăm sóc và quản lí.

**Comment by mynukeviet** [comment]
Hai điểm này lynx đã có rồi bạn nhé
