### ISSUE TITLE
workforce: thêm trang xem thông tin chi tiết nhân sự

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#6]

**Comment by hy3n0945972902vn** [comment]
đang thực hiện

**Comment by mynukeviet** [comment]
Thêm 2 nút sửa, xóa bên góc như ri nghe

![screenshot from 2018-08-11 08-01-15](https://user-images.githubusercontent.com/6407361/44126466-ac1ac4c8-a062-11e8-8750-4a26eb01b888.png)

**Comment by mynukeviet** [comment]
Sửa một số lỗi https://github.com/mynukeviet/lynx/commit/b0416fcb36e79fc93bdbb9018411fa6683687d70
