### ISSUE TITLE
customer: thêm quản lý đơn vị công tác

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#71]
Đơn vị công tác chuyển thành selectbox để có thể quản lý khách hàng theo đơn vị

![image](https://user-images.githubusercontent.com/6407361/49364436-e8179180-f716-11e8-9bc1-63bd2812eabd.png)

**Comment by huuthoqt1994** [comment]
đã xong https://github.com/huuthoqt1994/lynx/commit/e7491c4bd0fe4fceb9b95fbd5a4e0e5353336c00

**Comment by mynukeviet** [comment]
https://github.com/huuthoqt1994/lynx/commit/e7491c4bd0fe4fceb9b95fbd5a4e0e5353336c00#diff-ec9836bf188078841a7ef7fea6c8c860R101

Bảng unit ở đây không tồn tại

**Comment by mynukeviet** [comment]
Thống nhất đặt tên bảng đơn vị là `nv4_vi_customer_units`

**Comment by mynukeviet** [comment]
Để đơn giản, 1 khách hàng chỉ có thể thuộc 1 đơn vị thôi

**Comment by mynukeviet** [comment]
Cần có 1 trang để quản lý đơn vị trong admin nữa

**Comment by huuthoqt1994** [comment]
đã xong https://github.com/huuthoqt1994/lynx/commit/c798c371c3b8708b527bf96bf1622dc643f5f7b0

**Comment by mynukeviet** [comment]
Lỗi: Sửa 1 đơn vị, lưu lại, hắn tự thêm mới 1 đơn vị nữa

**Comment by mynukeviet** [comment]
Sửa dấu ------- thành `--- Chọn đơn vị công tác ---`

![image](https://user-images.githubusercontent.com/6407361/52555646-e5bf6b00-2e1c-11e9-885f-278bf05f5b53.png)
