### ISSUE TITLE
email: thêm lưu nháp

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#75]

**Comment by mynukeviet** [comment]
Nếu lưu nháp thì KHÔNG bắt buộc chọn người nhận, nhập nội dung.

Chỉ buộc nhập tiêu đề là đủ

**Comment by huuthoqt1994** [comment]
đã fix https://github.com/huuthoqt1994/lynx/commit/4789bb9c7df52ab4968e00d6af391028563ba47f

**Comment by huuthoqt1994** [comment]
đã fix https://github.com/huuthoqt1994/lynx/commit/5d9da57e06212c59915c24f68e1a856dac648566
