### ISSUE TITLE
Lỗi thêm khách hàng

### ISSUE THREAD

**Issue by hpleduit** [mynukeviet/lynx#83]
# Lỗi thêm khách hàng
 Thông báo từ Hệ thống
Nên chú ý Nên chú ý: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'share_acc' in 'field list'
# Lỗi vào danh sách liên hệ
Error on file /modules/customer/funcs/main.php line 125:

Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbcode2019.hp4_vi_customer_share_acc' doesn't exist' in E:\AppServ\www\code2019\modules\customer\funcs\main.php:125
Stack trace:
#0 E:\AppServ\www\code2019\modules\customer\funcs\main.php(125): PDO->prepare('SELECT COUNT(*)...')
#1 E:\AppServ\www\code2019\index.php(315): require('E:\\AppServ\\www\\...')
#2 {main}
  thrown

**Comment by mynukeviet** [comment]
Chào bạn, lỗi này xác định nguyên nhân do dữ liệu mẫu, không biết bạn có đang sử dụng lynx chưa ạ?
