### ISSUE TITLE
invoice: thêm đơn vị tính vô bảng chi tiết hóa đơn

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#84]
![image](https://user-images.githubusercontent.com/6407361/52024253-c24e1380-2532-11e9-93ee-bccccbbdcdff.png)

**Comment by huuthoqt1994** [comment]
đã xong https://github.com/huuthoqt1994/lynx/commit/263153fd59410831fa51aac6231d80622e4f5e7f
