### ISSUE TITLE
Dịch vụ không chọn dược đơn vị cho dịch vụ đó là năm, gói , hay gì nữa.

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#93]
Module services, đã có bảng price_unit trong CSDL nhưng chưa có form để quản lý. Thêm quản lý trong admin

**Comment by huuthoqt1994** [comment]
đã xong https://github.com/huuthoqt1994/lynx/commit/c90224cde2487fde1d886d050ba097e6415c62f8
