### ISSUE TITLE
invoice: pdf hóa đơn không có cột Đơn vị

### ISSUE THREAD

**Issue by mynukeviet** [mynukeviet/lynx#96]
![image](https://user-images.githubusercontent.com/6407361/55142959-596ccb80-5170-11e9-864e-6efd573bf21f.png)

**Comment by mynukeviet** [comment]
Lỗi xuất pdf anh đã sửa https://github.com/mynukeviet/lynx/commit/84be0a25c1d05e37084e4282dfcbc5a94c7dd8c7

Em fix tiếp như tiêu đề

**Comment by huuthoqt1994** [comment]
đã fix https://github.com/huuthoqt1994/lynx/commit/2ad9b3e028e3536501ab43751e6f2dceb4f435f8
