### ISSUE TITLE
Thêm trình soạn thảo ckeditor vào Báo cáo công việc

### ISSUE THREAD

**Issue by thanhchunghti** [mynukeviet/lynx#98]
Cần thêm ckeditor vào khung soạn thảo của mục Báo cáo công việc ạ.

**Comment by mynukeviet** [comment]
ACP / Báo cáo công việc / Cấu hình

Cuối trang có cái này nha bạn

![image](https://user-images.githubusercontent.com/6407361/56191858-625a0a00-6057-11e9-9c8d-1e98ed844160.png)
